import tkinter as tk
window = tk.Tk()
window.title("Haggle")
greeting = tk.Label(text="Hello, Haggle user!", foreground="blue", 
	width = 25, height = 10)  
greeting.pack()
usernameframe = tk.Frame()
usernamelabel = tk.Label(master = usernameframe, text="Enter your username!")
usernamelabel.pack()
usernameentry = tk.Entry(master = usernameframe)
usernameentry.pack()
usernameframe.pack()
loginbutton = tk.Button(text="Login", bg="#3DE100", width = 25, height = 2) 
loginbutton.pack()
quitbutton = tk.Button(text="Quit Haggle", command=quit)
quitbutton.pack()
window.mainloop()